# Generated by Django 4.2.1 on 2023-05-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.IntegerField()),
                ('downloads', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AdvantagesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='photos/advantages/')),
                ('image2', models.ImageField(upload_to='photos/advantages/')),
                ('image3', models.ImageField(upload_to='photos/advantages/')),
                ('image4', models.ImageField(upload_to='photos/advantages/')),
                ('image5', models.ImageField(upload_to='photos/advantages/')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technumber', models.CharField(max_length=25)),
                ('techmail', models.CharField(max_length=50)),
                ('accnumber', models.CharField(max_length=25)),
                ('accmail', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbimage', models.ImageField(upload_to='photos/feedback/')),
                ('name', models.CharField(max_length=80)),
                ('stars', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('fbtext', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='photos/rating/')),
                ('image2', models.ImageField(upload_to='photos/rating/')),
                ('image3', models.ImageField(upload_to='photos/rating/')),
                ('image4', models.ImageField(upload_to='photos/rating/')),
                ('image5', models.ImageField(upload_to='photos/rating/')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feedbacks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscribption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.CharField(max_length=50)),
                ('audience', models.CharField(max_length=50)),
                ('point1', models.CharField(max_length=100)),
                ('point2', models.CharField(max_length=100)),
                ('point3', models.CharField(max_length=100)),
                ('point4', models.CharField(max_length=100)),
                ('note', models.TextField()),
            ],
        ),
    ]
