# Generated by Django 4.2.1 on 2023-05-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeGreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.CharField(max_length=50)),
                ('audience', models.CharField(max_length=50)),
                ('point1', models.CharField(max_length=100)),
                ('point2', models.CharField(max_length=100)),
                ('point3', models.CharField(max_length=100)),
                ('point4', models.CharField(max_length=100)),
                ('note', models.TextField()),
            ],
        ),
    ]
