# Generated by Django 4.2.1 on 2023-05-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_advantagesimage_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbimage', models.ImageField(upload_to='photos/feedback/')),
                ('name', models.CharField(max_length=80)),
                ('stars', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('fbtext', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='advantagesimage',
            name='image1',
            field=models.ImageField(upload_to='photos/advantages/'),
        ),
        migrations.AlterField(
            model_name='advantagesimage',
            name='image2',
            field=models.ImageField(upload_to='photos/advantages/'),
        ),
        migrations.AlterField(
            model_name='advantagesimage',
            name='image3',
            field=models.ImageField(upload_to='photos/advantages/'),
        ),
        migrations.AlterField(
            model_name='advantagesimage',
            name='image4',
            field=models.ImageField(upload_to='photos/advantages/'),
        ),
        migrations.AlterField(
            model_name='advantagesimage',
            name='image5',
            field=models.ImageField(upload_to='photos/advantages/'),
        ),
    ]
