# Generated by Django 4.2.1 on 2023-05-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сontacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technumber', models.CharField(max_length=25)),
                ('techmail', models.CharField(max_length=50)),
                ('accnumber', models.CharField(max_length=25)),
                ('accmail', models.CharField(max_length=50)),
            ],
        ),
    ]
