# Generated by Django 4.2.1 on 2023-05-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_сontacts_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='photos/rating/')),
                ('image2', models.ImageField(upload_to='photos/rating/')),
                ('image3', models.ImageField(upload_to='photos/rating/')),
                ('image4', models.ImageField(upload_to='photos/rating/')),
                ('image5', models.ImageField(upload_to='photos/rating/')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feedbacks', models.IntegerField()),
            ],
        ),
    ]
